packages:
  - name: auto-scale
    shared: false
    functions:
      - name: main
        binary: false
        main: ""
        runtime: python:3.11
        web: false
        webSecure: false
        annotations: { }
        limits:
          logs: 16
          memory: 1024
          timeout: 10000

        triggers:
          - name: basic
            sourceType: scheduler
            sourceDetails:
              cron: "* * * * *"
              withBody: {}
