name: Linter

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

permissions:
  contents: read # This is required for actions/checkout

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ github.event.workflow_call.workflow_file }}"
  cancel-in-progress: true

jobs:
  linter:
    name: Testing build
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install virtualenv
        run: |
          pip install virtualenv

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          no_auth: true

      - name: Init DigitalOcean API client
        run: |
          doctl auth init
      

      - name: Deploy to Digital Ocean
        run: doctl serverless deploy .